import { useState } from "react";
import Head from "next/head";
import Data from "./data";
import { Button, Divider } from "@mui/material";
import ChartModal from "../components/ChartModal";
import DownloadCitation from "../components/DownloadCitation";

// type
type Datatype = {
  labels: string[];
  datasets: [
    {
      label: string;
      data: string[];
      backgroundColor?: string[];
    }
  ];
};

export default function Home() {
  const [chartModal, openChartModal] = useState(false);
  const [citationModal, openCitationModal] = useState(false)
  const [userData, setUserData] = useState<Datatype>({
    labels: Data.map((user: any) => user.year),
    datasets: [
      {
        label: "Users Gained",
        data: Data.map((user: unknown) => user?.userGain),
        backgroundColor: [
          "#003f5c",
          "#58508d",
          "#bc5090",
          "#ff6361",
          "#ffa600",
        ],
      },
    ],
  });

  // Close Modal
  function handleClose() {
    openChartModal(false);
    openCitationModal(false);
  }
  return (
    <>
      <Head>
        <title>Useful Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ width: "100vw", padding: "1rem" }}>
        <h1 style={{ textAlign: "center" }}>Modal</h1>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            marginTop: "4rem",
          }}
        >
          <div
            style={{
              border: "1px solid cyan",
              width: 400,
              textAlign: "center",
            }}
          >
            <div>
              <Button onClick={() => openChartModal(true)}>
                Open Chart modal
              </Button>
            </div>
            <Button onClick={() => openCitationModal(true)}>Download Citation</Button>
          </div>
          <ChartModal
            isOpen={chartModal}
            handleClose={handleClose}
            chartData={userData}
          />
          <DownloadCitation isOpen={citationModal} handleClose={handleClose} />
        </div>
      </div>
    </>
  );
}
